name: Android CI

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Generate Platform Folders
      run: flutter create --platforms=android .
        
    - name: Inject Internet Permissions
      run: sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Google Play App Bundle (.aab)
      run: flutter build appbundle --release
      
    - name: Build Optimized APK (.apk)
      run: flutter build apk --release
        
    - name: Secure & Rename APK
      run: |
        # This bypasses the buggy Flutter APK locator
        APK_PATH=$(find build -type f -name "*.apk" | grep -v "test" | head -n 1)
        mv "$APK_PATH" Optimized-Release.apk
        
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: PlayStore-Release-AAB
        path: build/app/outputs/bundle/release/app-release.aab
        
    - name: Upload Optimized APK
      uses: actions/upload-artifact@v4
      with:
        name: Direct-Install-APK
        path: Optimized-Release.apk
